version: "3.8"
services:
  todo-app:
    image: eldrian/todoapp:3.0
    container_name: todoapp
    links:
      - todo-database
    ports:
      - 8888:8080
    depends_on:
      - todo-database
    volumes:
      - database_data:/usr/app/postgres/data
  todo-database:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5555:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database_data:/var/lib/postgresql/data
volumes: 
  database_data: