version: "3.8"
services:
  todo-app:
    image: eldrian/todoapp:1.0
    container_name: todoapp
    links:
      - todo-database
    ports:
      - 8888:8080
  todo-database:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5555:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data